<?xml version="1.0" encoding="utf-8"?><Database Name="TopScores" Class="HighscoreDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\TopScores.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="WindowsFormsApp1.Properties.Settings" SettingsPropertyName="TopScoresConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HighScore" Member="HighScore">
    <Type Name="HighScore">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>